services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "8080:8080"
    environment:
    # environement variables coming from python .env file
      - DB_HOST=${DB_HOST}         
      - DB_NAME=${DB_NAME}        
      - DB_USER=${DB_USER}         
      - DB_PASSWORD=${DB_PASSWORD}
      - FLASK_APP=src.app
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - .:/app
    command: ["./setup.sh"]